// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace edTechSpark.Core.Entities
{
    public partial class Order
    {
        public Order()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public string Id { get; set; }
        public int UserId { get; set; }
        public string PaymentId { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}